### ISSUE TITLE
Specflow 3 - ScenarioContext.Current is obsolete

### ISSUE THREAD

**Issue by drosenba** [wenyuansong/Specflow.DSL#2]
I see you recently did a commit for "update to fit Specflow 3 Plugin API requirements", yet you are still using ScenarioContext.Current which is not obsolete.

**Comment by wenyuansong** [comment]
thanks for raising this issue. I updated the code to make it work with specflow 3 and I'm aware of the obsolete warning. 
Will find a solution to replace ScenarioContext

**Comment by wenyuansong** [comment]
> I see you recently did a commit for "update to fit Specflow 3 Plugin API requirements", yet you are still using ScenarioContext.Current which is not obsolete.

@drosenba , I've updated the code to remove using ScenarioContext.current
